spring:
  #redis
  redis:
    # Redis服务器地址
    host: 120.79.210.194
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: bb123456
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 控制一个pool最多有多少个状态为idle(空闲的)的jedis实例
      max-idle: 100
      # 控制一个pool最少有多少个状态为idle(空闲的)的jedis实例
      min-idle: 0
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      # 表示当borrow(引入)一个jedis实例时，最大的等待时间，如果超过等待时间(毫秒)，则直接抛出JedisConnectionException；
      max-wait: 1000
    # 连接超时时间（毫秒）
    timeout: 3000